# Your personal GitHub token
github_token: your-personal-github-token

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: portalium

# Virtual machine IP
ip: 192.168.83.137

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
